---
- name: Install Apache, a web server
  hosts: all
  tasks:
    - name: Ensure the httpd software is installed
      ansible.builtin.package:
        name: httpd
        state: present
    - name: Ensure the httpd service is enabled and started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
